// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream_out/chromecast/cast_channel.proto

#ifndef PROTOBUF_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto__INCLUDED
#define PROTOBUF_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

namespace castchannel {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();
void protobuf_InitDefaults_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();
void protobuf_AssignDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();
void protobuf_ShutdownFile_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();

class AuthChallenge;
class AuthError;
class AuthResponse;
class CastMessage;
class DeviceAuthMessage;

enum CastMessage_ProtocolVersion {
  CastMessage_ProtocolVersion_CASTV2_1_0 = 0
};
bool CastMessage_ProtocolVersion_IsValid(int value);
const CastMessage_ProtocolVersion CastMessage_ProtocolVersion_ProtocolVersion_MIN = CastMessage_ProtocolVersion_CASTV2_1_0;
const CastMessage_ProtocolVersion CastMessage_ProtocolVersion_ProtocolVersion_MAX = CastMessage_ProtocolVersion_CASTV2_1_0;
const int CastMessage_ProtocolVersion_ProtocolVersion_ARRAYSIZE = CastMessage_ProtocolVersion_ProtocolVersion_MAX + 1;

enum CastMessage_PayloadType {
  CastMessage_PayloadType_STRING = 0,
  CastMessage_PayloadType_BINARY = 1
};
bool CastMessage_PayloadType_IsValid(int value);
const CastMessage_PayloadType CastMessage_PayloadType_PayloadType_MIN = CastMessage_PayloadType_STRING;
const CastMessage_PayloadType CastMessage_PayloadType_PayloadType_MAX = CastMessage_PayloadType_BINARY;
const int CastMessage_PayloadType_PayloadType_ARRAYSIZE = CastMessage_PayloadType_PayloadType_MAX + 1;

enum AuthError_ErrorType {
  AuthError_ErrorType_INTERNAL_ERROR = 0,
  AuthError_ErrorType_NO_TLS = 1
};
bool AuthError_ErrorType_IsValid(int value);
const AuthError_ErrorType AuthError_ErrorType_ErrorType_MIN = AuthError_ErrorType_INTERNAL_ERROR;
const AuthError_ErrorType AuthError_ErrorType_ErrorType_MAX = AuthError_ErrorType_NO_TLS;
const int AuthError_ErrorType_ErrorType_ARRAYSIZE = AuthError_ErrorType_ErrorType_MAX + 1;

// ===================================================================

class CastMessage : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:castchannel.CastMessage) */ {
 public:
  CastMessage();
  virtual ~CastMessage();

  CastMessage(const CastMessage& from);

  inline CastMessage& operator=(const CastMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const CastMessage& default_instance();

  static const CastMessage* internal_default_instance();

  void Swap(CastMessage* other);

  // implements Message ----------------------------------------------

  inline CastMessage* New() const { return New(NULL); }

  CastMessage* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CastMessage& from);
  void MergeFrom(const CastMessage& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CastMessage* other);
  void UnsafeMergeFrom(const CastMessage& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  typedef CastMessage_ProtocolVersion ProtocolVersion;
  static const ProtocolVersion CASTV2_1_0 =
    CastMessage_ProtocolVersion_CASTV2_1_0;
  static inline bool ProtocolVersion_IsValid(int value) {
    return CastMessage_ProtocolVersion_IsValid(value);
  }
  static const ProtocolVersion ProtocolVersion_MIN =
    CastMessage_ProtocolVersion_ProtocolVersion_MIN;
  static const ProtocolVersion ProtocolVersion_MAX =
    CastMessage_ProtocolVersion_ProtocolVersion_MAX;
  static const int ProtocolVersion_ARRAYSIZE =
    CastMessage_ProtocolVersion_ProtocolVersion_ARRAYSIZE;

  typedef CastMessage_PayloadType PayloadType;
  static const PayloadType STRING =
    CastMessage_PayloadType_STRING;
  static const PayloadType BINARY =
    CastMessage_PayloadType_BINARY;
  static inline bool PayloadType_IsValid(int value) {
    return CastMessage_PayloadType_IsValid(value);
  }
  static const PayloadType PayloadType_MIN =
    CastMessage_PayloadType_PayloadType_MIN;
  static const PayloadType PayloadType_MAX =
    CastMessage_PayloadType_PayloadType_MAX;
  static const int PayloadType_ARRAYSIZE =
    CastMessage_PayloadType_PayloadType_ARRAYSIZE;

  // accessors -------------------------------------------------------

  // required .castchannel.CastMessage.ProtocolVersion protocol_version = 1;
  bool has_protocol_version() const;
  void clear_protocol_version();
  static const int kProtocolVersionFieldNumber = 1;
  ::castchannel::CastMessage_ProtocolVersion protocol_version() const;
  void set_protocol_version(::castchannel::CastMessage_ProtocolVersion value);

  // required string source_id = 2;
  bool has_source_id() const;
  void clear_source_id();
  static const int kSourceIdFieldNumber = 2;
  const ::std::string& source_id() const;
  void set_source_id(const ::std::string& value);
  void set_source_id(const char* value);
  void set_source_id(const char* value, size_t size);
  ::std::string* mutable_source_id();
  ::std::string* release_source_id();
  void set_allocated_source_id(::std::string* source_id);

  // required string destination_id = 3;
  bool has_destination_id() const;
  void clear_destination_id();
  static const int kDestinationIdFieldNumber = 3;
  const ::std::string& destination_id() const;
  void set_destination_id(const ::std::string& value);
  void set_destination_id(const char* value);
  void set_destination_id(const char* value, size_t size);
  ::std::string* mutable_destination_id();
  ::std::string* release_destination_id();
  void set_allocated_destination_id(::std::string* destination_id);

  // required string namespace = 4;
  bool has_namespace_() const;
  void clear_namespace_();
  static const int kNamespaceFieldNumber = 4;
  const ::std::string& namespace_() const;
  void set_namespace_(const ::std::string& value);
  void set_namespace_(const char* value);
  void set_namespace_(const char* value, size_t size);
  ::std::string* mutable_namespace_();
  ::std::string* release_namespace_();
  void set_allocated_namespace_(::std::string* namespace_);

  // required .castchannel.CastMessage.PayloadType payload_type = 5;
  bool has_payload_type() const;
  void clear_payload_type();
  static const int kPayloadTypeFieldNumber = 5;
  ::castchannel::CastMessage_PayloadType payload_type() const;
  void set_payload_type(::castchannel::CastMessage_PayloadType value);

  // optional string payload_utf8 = 6;
  bool has_payload_utf8() const;
  void clear_payload_utf8();
  static const int kPayloadUtf8FieldNumber = 6;
  const ::std::string& payload_utf8() const;
  void set_payload_utf8(const ::std::string& value);
  void set_payload_utf8(const char* value);
  void set_payload_utf8(const char* value, size_t size);
  ::std::string* mutable_payload_utf8();
  ::std::string* release_payload_utf8();
  void set_allocated_payload_utf8(::std::string* payload_utf8);

  // optional bytes payload_binary = 7;
  bool has_payload_binary() const;
  void clear_payload_binary();
  static const int kPayloadBinaryFieldNumber = 7;
  const ::std::string& payload_binary() const;
  void set_payload_binary(const ::std::string& value);
  void set_payload_binary(const char* value);
  void set_payload_binary(const void* value, size_t size);
  ::std::string* mutable_payload_binary();
  ::std::string* release_payload_binary();
  void set_allocated_payload_binary(::std::string* payload_binary);

  // @@protoc_insertion_point(class_scope:castchannel.CastMessage)
 private:
  inline void set_has_protocol_version();
  inline void clear_has_protocol_version();
  inline void set_has_source_id();
  inline void clear_has_source_id();
  inline void set_has_destination_id();
  inline void clear_has_destination_id();
  inline void set_has_namespace_();
  inline void clear_has_namespace_();
  inline void set_has_payload_type();
  inline void clear_has_payload_type();
  inline void set_has_payload_utf8();
  inline void clear_has_payload_utf8();
  inline void set_has_payload_binary();
  inline void clear_has_payload_binary();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr source_id_;
  ::google::protobuf::internal::ArenaStringPtr destination_id_;
  ::google::protobuf::internal::ArenaStringPtr namespace__;
  ::google::protobuf::internal::ArenaStringPtr payload_utf8_;
  ::google::protobuf::internal::ArenaStringPtr payload_binary_;
  int protocol_version_;
  int payload_type_;
  friend void  protobuf_InitDefaults_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto_impl();
  friend void  protobuf_AddDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto_impl();
  friend void protobuf_AssignDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();
  friend void protobuf_ShutdownFile_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CastMessage> CastMessage_default_instance_;

// -------------------------------------------------------------------

class AuthChallenge : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:castchannel.AuthChallenge) */ {
 public:
  AuthChallenge();
  virtual ~AuthChallenge();

  AuthChallenge(const AuthChallenge& from);

  inline AuthChallenge& operator=(const AuthChallenge& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const AuthChallenge& default_instance();

  static const AuthChallenge* internal_default_instance();

  void Swap(AuthChallenge* other);

  // implements Message ----------------------------------------------

  inline AuthChallenge* New() const { return New(NULL); }

  AuthChallenge* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const AuthChallenge& from);
  void MergeFrom(const AuthChallenge& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AuthChallenge* other);
  void UnsafeMergeFrom(const AuthChallenge& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:castchannel.AuthChallenge)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto_impl();
  friend void  protobuf_AddDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto_impl();
  friend void protobuf_AssignDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();
  friend void protobuf_ShutdownFile_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<AuthChallenge> AuthChallenge_default_instance_;

// -------------------------------------------------------------------

class AuthResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:castchannel.AuthResponse) */ {
 public:
  AuthResponse();
  virtual ~AuthResponse();

  AuthResponse(const AuthResponse& from);

  inline AuthResponse& operator=(const AuthResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const AuthResponse& default_instance();

  static const AuthResponse* internal_default_instance();

  void Swap(AuthResponse* other);

  // implements Message ----------------------------------------------

  inline AuthResponse* New() const { return New(NULL); }

  AuthResponse* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const AuthResponse& from);
  void MergeFrom(const AuthResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AuthResponse* other);
  void UnsafeMergeFrom(const AuthResponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes signature = 1;
  bool has_signature() const;
  void clear_signature();
  static const int kSignatureFieldNumber = 1;
  const ::std::string& signature() const;
  void set_signature(const ::std::string& value);
  void set_signature(const char* value);
  void set_signature(const void* value, size_t size);
  ::std::string* mutable_signature();
  ::std::string* release_signature();
  void set_allocated_signature(::std::string* signature);

  // required bytes client_auth_certificate = 2;
  bool has_client_auth_certificate() const;
  void clear_client_auth_certificate();
  static const int kClientAuthCertificateFieldNumber = 2;
  const ::std::string& client_auth_certificate() const;
  void set_client_auth_certificate(const ::std::string& value);
  void set_client_auth_certificate(const char* value);
  void set_client_auth_certificate(const void* value, size_t size);
  ::std::string* mutable_client_auth_certificate();
  ::std::string* release_client_auth_certificate();
  void set_allocated_client_auth_certificate(::std::string* client_auth_certificate);

  // @@protoc_insertion_point(class_scope:castchannel.AuthResponse)
 private:
  inline void set_has_signature();
  inline void clear_has_signature();
  inline void set_has_client_auth_certificate();
  inline void clear_has_client_auth_certificate();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr signature_;
  ::google::protobuf::internal::ArenaStringPtr client_auth_certificate_;
  friend void  protobuf_InitDefaults_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto_impl();
  friend void  protobuf_AddDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto_impl();
  friend void protobuf_AssignDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();
  friend void protobuf_ShutdownFile_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<AuthResponse> AuthResponse_default_instance_;

// -------------------------------------------------------------------

class AuthError : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:castchannel.AuthError) */ {
 public:
  AuthError();
  virtual ~AuthError();

  AuthError(const AuthError& from);

  inline AuthError& operator=(const AuthError& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const AuthError& default_instance();

  static const AuthError* internal_default_instance();

  void Swap(AuthError* other);

  // implements Message ----------------------------------------------

  inline AuthError* New() const { return New(NULL); }

  AuthError* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const AuthError& from);
  void MergeFrom(const AuthError& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AuthError* other);
  void UnsafeMergeFrom(const AuthError& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  typedef AuthError_ErrorType ErrorType;
  static const ErrorType INTERNAL_ERROR =
    AuthError_ErrorType_INTERNAL_ERROR;
  static const ErrorType NO_TLS =
    AuthError_ErrorType_NO_TLS;
  static inline bool ErrorType_IsValid(int value) {
    return AuthError_ErrorType_IsValid(value);
  }
  static const ErrorType ErrorType_MIN =
    AuthError_ErrorType_ErrorType_MIN;
  static const ErrorType ErrorType_MAX =
    AuthError_ErrorType_ErrorType_MAX;
  static const int ErrorType_ARRAYSIZE =
    AuthError_ErrorType_ErrorType_ARRAYSIZE;

  // accessors -------------------------------------------------------

  // required .castchannel.AuthError.ErrorType error_type = 1;
  bool has_error_type() const;
  void clear_error_type();
  static const int kErrorTypeFieldNumber = 1;
  ::castchannel::AuthError_ErrorType error_type() const;
  void set_error_type(::castchannel::AuthError_ErrorType value);

  // @@protoc_insertion_point(class_scope:castchannel.AuthError)
 private:
  inline void set_has_error_type();
  inline void clear_has_error_type();

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  int error_type_;
  friend void  protobuf_InitDefaults_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto_impl();
  friend void  protobuf_AddDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto_impl();
  friend void protobuf_AssignDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();
  friend void protobuf_ShutdownFile_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<AuthError> AuthError_default_instance_;

// -------------------------------------------------------------------

class DeviceAuthMessage : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:castchannel.DeviceAuthMessage) */ {
 public:
  DeviceAuthMessage();
  virtual ~DeviceAuthMessage();

  DeviceAuthMessage(const DeviceAuthMessage& from);

  inline DeviceAuthMessage& operator=(const DeviceAuthMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const DeviceAuthMessage& default_instance();

  static const DeviceAuthMessage* internal_default_instance();

  void Swap(DeviceAuthMessage* other);

  // implements Message ----------------------------------------------

  inline DeviceAuthMessage* New() const { return New(NULL); }

  DeviceAuthMessage* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DeviceAuthMessage& from);
  void MergeFrom(const DeviceAuthMessage& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DeviceAuthMessage* other);
  void UnsafeMergeFrom(const DeviceAuthMessage& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .castchannel.AuthChallenge challenge = 1;
  bool has_challenge() const;
  void clear_challenge();
  static const int kChallengeFieldNumber = 1;
  const ::castchannel::AuthChallenge& challenge() const;
  ::castchannel::AuthChallenge* mutable_challenge();
  ::castchannel::AuthChallenge* release_challenge();
  void set_allocated_challenge(::castchannel::AuthChallenge* challenge);

  // optional .castchannel.AuthResponse response = 2;
  bool has_response() const;
  void clear_response();
  static const int kResponseFieldNumber = 2;
  const ::castchannel::AuthResponse& response() const;
  ::castchannel::AuthResponse* mutable_response();
  ::castchannel::AuthResponse* release_response();
  void set_allocated_response(::castchannel::AuthResponse* response);

  // optional .castchannel.AuthError error = 3;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 3;
  const ::castchannel::AuthError& error() const;
  ::castchannel::AuthError* mutable_error();
  ::castchannel::AuthError* release_error();
  void set_allocated_error(::castchannel::AuthError* error);

  // @@protoc_insertion_point(class_scope:castchannel.DeviceAuthMessage)
 private:
  inline void set_has_challenge();
  inline void clear_has_challenge();
  inline void set_has_response();
  inline void clear_has_response();
  inline void set_has_error();
  inline void clear_has_error();

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::castchannel::AuthChallenge* challenge_;
  ::castchannel::AuthResponse* response_;
  ::castchannel::AuthError* error_;
  friend void  protobuf_InitDefaults_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto_impl();
  friend void  protobuf_AddDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto_impl();
  friend void protobuf_AssignDesc_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();
  friend void protobuf_ShutdownFile_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<DeviceAuthMessage> DeviceAuthMessage_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CastMessage

// required .castchannel.CastMessage.ProtocolVersion protocol_version = 1;
inline bool CastMessage::has_protocol_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CastMessage::set_has_protocol_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CastMessage::clear_has_protocol_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CastMessage::clear_protocol_version() {
  protocol_version_ = 0;
  clear_has_protocol_version();
}
inline ::castchannel::CastMessage_ProtocolVersion CastMessage::protocol_version() const {
  // @@protoc_insertion_point(field_get:castchannel.CastMessage.protocol_version)
  return static_cast< ::castchannel::CastMessage_ProtocolVersion >(protocol_version_);
}
inline void CastMessage::set_protocol_version(::castchannel::CastMessage_ProtocolVersion value) {
  assert(::castchannel::CastMessage_ProtocolVersion_IsValid(value));
  set_has_protocol_version();
  protocol_version_ = value;
  // @@protoc_insertion_point(field_set:castchannel.CastMessage.protocol_version)
}

// required string source_id = 2;
inline bool CastMessage::has_source_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CastMessage::set_has_source_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CastMessage::clear_has_source_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CastMessage::clear_source_id() {
  source_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_source_id();
}
inline const ::std::string& CastMessage::source_id() const {
  // @@protoc_insertion_point(field_get:castchannel.CastMessage.source_id)
  return source_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CastMessage::set_source_id(const ::std::string& value) {
  set_has_source_id();
  source_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:castchannel.CastMessage.source_id)
}
inline void CastMessage::set_source_id(const char* value) {
  set_has_source_id();
  source_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:castchannel.CastMessage.source_id)
}
inline void CastMessage::set_source_id(const char* value, size_t size) {
  set_has_source_id();
  source_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:castchannel.CastMessage.source_id)
}
inline ::std::string* CastMessage::mutable_source_id() {
  set_has_source_id();
  // @@protoc_insertion_point(field_mutable:castchannel.CastMessage.source_id)
  return source_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CastMessage::release_source_id() {
  // @@protoc_insertion_point(field_release:castchannel.CastMessage.source_id)
  clear_has_source_id();
  return source_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CastMessage::set_allocated_source_id(::std::string* source_id) {
  if (source_id != NULL) {
    set_has_source_id();
  } else {
    clear_has_source_id();
  }
  source_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source_id);
  // @@protoc_insertion_point(field_set_allocated:castchannel.CastMessage.source_id)
}

// required string destination_id = 3;
inline bool CastMessage::has_destination_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CastMessage::set_has_destination_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CastMessage::clear_has_destination_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CastMessage::clear_destination_id() {
  destination_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_destination_id();
}
inline const ::std::string& CastMessage::destination_id() const {
  // @@protoc_insertion_point(field_get:castchannel.CastMessage.destination_id)
  return destination_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CastMessage::set_destination_id(const ::std::string& value) {
  set_has_destination_id();
  destination_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:castchannel.CastMessage.destination_id)
}
inline void CastMessage::set_destination_id(const char* value) {
  set_has_destination_id();
  destination_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:castchannel.CastMessage.destination_id)
}
inline void CastMessage::set_destination_id(const char* value, size_t size) {
  set_has_destination_id();
  destination_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:castchannel.CastMessage.destination_id)
}
inline ::std::string* CastMessage::mutable_destination_id() {
  set_has_destination_id();
  // @@protoc_insertion_point(field_mutable:castchannel.CastMessage.destination_id)
  return destination_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CastMessage::release_destination_id() {
  // @@protoc_insertion_point(field_release:castchannel.CastMessage.destination_id)
  clear_has_destination_id();
  return destination_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CastMessage::set_allocated_destination_id(::std::string* destination_id) {
  if (destination_id != NULL) {
    set_has_destination_id();
  } else {
    clear_has_destination_id();
  }
  destination_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), destination_id);
  // @@protoc_insertion_point(field_set_allocated:castchannel.CastMessage.destination_id)
}

// required string namespace = 4;
inline bool CastMessage::has_namespace_() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CastMessage::set_has_namespace_() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CastMessage::clear_has_namespace_() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CastMessage::clear_namespace_() {
  namespace__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_namespace_();
}
inline const ::std::string& CastMessage::namespace_() const {
  // @@protoc_insertion_point(field_get:castchannel.CastMessage.namespace)
  return namespace__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CastMessage::set_namespace_(const ::std::string& value) {
  set_has_namespace_();
  namespace__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:castchannel.CastMessage.namespace)
}
inline void CastMessage::set_namespace_(const char* value) {
  set_has_namespace_();
  namespace__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:castchannel.CastMessage.namespace)
}
inline void CastMessage::set_namespace_(const char* value, size_t size) {
  set_has_namespace_();
  namespace__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:castchannel.CastMessage.namespace)
}
inline ::std::string* CastMessage::mutable_namespace_() {
  set_has_namespace_();
  // @@protoc_insertion_point(field_mutable:castchannel.CastMessage.namespace)
  return namespace__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CastMessage::release_namespace_() {
  // @@protoc_insertion_point(field_release:castchannel.CastMessage.namespace)
  clear_has_namespace_();
  return namespace__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CastMessage::set_allocated_namespace_(::std::string* namespace_) {
  if (namespace_ != NULL) {
    set_has_namespace_();
  } else {
    clear_has_namespace_();
  }
  namespace__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), namespace_);
  // @@protoc_insertion_point(field_set_allocated:castchannel.CastMessage.namespace)
}

// required .castchannel.CastMessage.PayloadType payload_type = 5;
inline bool CastMessage::has_payload_type() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CastMessage::set_has_payload_type() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CastMessage::clear_has_payload_type() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CastMessage::clear_payload_type() {
  payload_type_ = 0;
  clear_has_payload_type();
}
inline ::castchannel::CastMessage_PayloadType CastMessage::payload_type() const {
  // @@protoc_insertion_point(field_get:castchannel.CastMessage.payload_type)
  return static_cast< ::castchannel::CastMessage_PayloadType >(payload_type_);
}
inline void CastMessage::set_payload_type(::castchannel::CastMessage_PayloadType value) {
  assert(::castchannel::CastMessage_PayloadType_IsValid(value));
  set_has_payload_type();
  payload_type_ = value;
  // @@protoc_insertion_point(field_set:castchannel.CastMessage.payload_type)
}

// optional string payload_utf8 = 6;
inline bool CastMessage::has_payload_utf8() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CastMessage::set_has_payload_utf8() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CastMessage::clear_has_payload_utf8() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CastMessage::clear_payload_utf8() {
  payload_utf8_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_payload_utf8();
}
inline const ::std::string& CastMessage::payload_utf8() const {
  // @@protoc_insertion_point(field_get:castchannel.CastMessage.payload_utf8)
  return payload_utf8_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CastMessage::set_payload_utf8(const ::std::string& value) {
  set_has_payload_utf8();
  payload_utf8_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:castchannel.CastMessage.payload_utf8)
}
inline void CastMessage::set_payload_utf8(const char* value) {
  set_has_payload_utf8();
  payload_utf8_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:castchannel.CastMessage.payload_utf8)
}
inline void CastMessage::set_payload_utf8(const char* value, size_t size) {
  set_has_payload_utf8();
  payload_utf8_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:castchannel.CastMessage.payload_utf8)
}
inline ::std::string* CastMessage::mutable_payload_utf8() {
  set_has_payload_utf8();
  // @@protoc_insertion_point(field_mutable:castchannel.CastMessage.payload_utf8)
  return payload_utf8_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CastMessage::release_payload_utf8() {
  // @@protoc_insertion_point(field_release:castchannel.CastMessage.payload_utf8)
  clear_has_payload_utf8();
  return payload_utf8_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CastMessage::set_allocated_payload_utf8(::std::string* payload_utf8) {
  if (payload_utf8 != NULL) {
    set_has_payload_utf8();
  } else {
    clear_has_payload_utf8();
  }
  payload_utf8_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload_utf8);
  // @@protoc_insertion_point(field_set_allocated:castchannel.CastMessage.payload_utf8)
}

// optional bytes payload_binary = 7;
inline bool CastMessage::has_payload_binary() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CastMessage::set_has_payload_binary() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CastMessage::clear_has_payload_binary() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CastMessage::clear_payload_binary() {
  payload_binary_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_payload_binary();
}
inline const ::std::string& CastMessage::payload_binary() const {
  // @@protoc_insertion_point(field_get:castchannel.CastMessage.payload_binary)
  return payload_binary_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CastMessage::set_payload_binary(const ::std::string& value) {
  set_has_payload_binary();
  payload_binary_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:castchannel.CastMessage.payload_binary)
}
inline void CastMessage::set_payload_binary(const char* value) {
  set_has_payload_binary();
  payload_binary_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:castchannel.CastMessage.payload_binary)
}
inline void CastMessage::set_payload_binary(const void* value, size_t size) {
  set_has_payload_binary();
  payload_binary_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:castchannel.CastMessage.payload_binary)
}
inline ::std::string* CastMessage::mutable_payload_binary() {
  set_has_payload_binary();
  // @@protoc_insertion_point(field_mutable:castchannel.CastMessage.payload_binary)
  return payload_binary_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CastMessage::release_payload_binary() {
  // @@protoc_insertion_point(field_release:castchannel.CastMessage.payload_binary)
  clear_has_payload_binary();
  return payload_binary_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CastMessage::set_allocated_payload_binary(::std::string* payload_binary) {
  if (payload_binary != NULL) {
    set_has_payload_binary();
  } else {
    clear_has_payload_binary();
  }
  payload_binary_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload_binary);
  // @@protoc_insertion_point(field_set_allocated:castchannel.CastMessage.payload_binary)
}

inline const CastMessage* CastMessage::internal_default_instance() {
  return &CastMessage_default_instance_.get();
}
// -------------------------------------------------------------------

// AuthChallenge

inline const AuthChallenge* AuthChallenge::internal_default_instance() {
  return &AuthChallenge_default_instance_.get();
}
// -------------------------------------------------------------------

// AuthResponse

// required bytes signature = 1;
inline bool AuthResponse::has_signature() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AuthResponse::set_has_signature() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AuthResponse::clear_has_signature() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AuthResponse::clear_signature() {
  signature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_signature();
}
inline const ::std::string& AuthResponse::signature() const {
  // @@protoc_insertion_point(field_get:castchannel.AuthResponse.signature)
  return signature_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthResponse::set_signature(const ::std::string& value) {
  set_has_signature();
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:castchannel.AuthResponse.signature)
}
inline void AuthResponse::set_signature(const char* value) {
  set_has_signature();
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:castchannel.AuthResponse.signature)
}
inline void AuthResponse::set_signature(const void* value, size_t size) {
  set_has_signature();
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:castchannel.AuthResponse.signature)
}
inline ::std::string* AuthResponse::mutable_signature() {
  set_has_signature();
  // @@protoc_insertion_point(field_mutable:castchannel.AuthResponse.signature)
  return signature_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthResponse::release_signature() {
  // @@protoc_insertion_point(field_release:castchannel.AuthResponse.signature)
  clear_has_signature();
  return signature_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthResponse::set_allocated_signature(::std::string* signature) {
  if (signature != NULL) {
    set_has_signature();
  } else {
    clear_has_signature();
  }
  signature_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), signature);
  // @@protoc_insertion_point(field_set_allocated:castchannel.AuthResponse.signature)
}

// required bytes client_auth_certificate = 2;
inline bool AuthResponse::has_client_auth_certificate() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AuthResponse::set_has_client_auth_certificate() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AuthResponse::clear_has_client_auth_certificate() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AuthResponse::clear_client_auth_certificate() {
  client_auth_certificate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_client_auth_certificate();
}
inline const ::std::string& AuthResponse::client_auth_certificate() const {
  // @@protoc_insertion_point(field_get:castchannel.AuthResponse.client_auth_certificate)
  return client_auth_certificate_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthResponse::set_client_auth_certificate(const ::std::string& value) {
  set_has_client_auth_certificate();
  client_auth_certificate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:castchannel.AuthResponse.client_auth_certificate)
}
inline void AuthResponse::set_client_auth_certificate(const char* value) {
  set_has_client_auth_certificate();
  client_auth_certificate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:castchannel.AuthResponse.client_auth_certificate)
}
inline void AuthResponse::set_client_auth_certificate(const void* value, size_t size) {
  set_has_client_auth_certificate();
  client_auth_certificate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:castchannel.AuthResponse.client_auth_certificate)
}
inline ::std::string* AuthResponse::mutable_client_auth_certificate() {
  set_has_client_auth_certificate();
  // @@protoc_insertion_point(field_mutable:castchannel.AuthResponse.client_auth_certificate)
  return client_auth_certificate_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthResponse::release_client_auth_certificate() {
  // @@protoc_insertion_point(field_release:castchannel.AuthResponse.client_auth_certificate)
  clear_has_client_auth_certificate();
  return client_auth_certificate_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthResponse::set_allocated_client_auth_certificate(::std::string* client_auth_certificate) {
  if (client_auth_certificate != NULL) {
    set_has_client_auth_certificate();
  } else {
    clear_has_client_auth_certificate();
  }
  client_auth_certificate_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), client_auth_certificate);
  // @@protoc_insertion_point(field_set_allocated:castchannel.AuthResponse.client_auth_certificate)
}

inline const AuthResponse* AuthResponse::internal_default_instance() {
  return &AuthResponse_default_instance_.get();
}
// -------------------------------------------------------------------

// AuthError

// required .castchannel.AuthError.ErrorType error_type = 1;
inline bool AuthError::has_error_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AuthError::set_has_error_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AuthError::clear_has_error_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AuthError::clear_error_type() {
  error_type_ = 0;
  clear_has_error_type();
}
inline ::castchannel::AuthError_ErrorType AuthError::error_type() const {
  // @@protoc_insertion_point(field_get:castchannel.AuthError.error_type)
  return static_cast< ::castchannel::AuthError_ErrorType >(error_type_);
}
inline void AuthError::set_error_type(::castchannel::AuthError_ErrorType value) {
  assert(::castchannel::AuthError_ErrorType_IsValid(value));
  set_has_error_type();
  error_type_ = value;
  // @@protoc_insertion_point(field_set:castchannel.AuthError.error_type)
}

inline const AuthError* AuthError::internal_default_instance() {
  return &AuthError_default_instance_.get();
}
// -------------------------------------------------------------------

// DeviceAuthMessage

// optional .castchannel.AuthChallenge challenge = 1;
inline bool DeviceAuthMessage::has_challenge() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeviceAuthMessage::set_has_challenge() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeviceAuthMessage::clear_has_challenge() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeviceAuthMessage::clear_challenge() {
  if (challenge_ != NULL) challenge_->::castchannel::AuthChallenge::Clear();
  clear_has_challenge();
}
inline const ::castchannel::AuthChallenge& DeviceAuthMessage::challenge() const {
  // @@protoc_insertion_point(field_get:castchannel.DeviceAuthMessage.challenge)
  return challenge_ != NULL ? *challenge_
                         : *::castchannel::AuthChallenge::internal_default_instance();
}
inline ::castchannel::AuthChallenge* DeviceAuthMessage::mutable_challenge() {
  set_has_challenge();
  if (challenge_ == NULL) {
    challenge_ = new ::castchannel::AuthChallenge;
  }
  // @@protoc_insertion_point(field_mutable:castchannel.DeviceAuthMessage.challenge)
  return challenge_;
}
inline ::castchannel::AuthChallenge* DeviceAuthMessage::release_challenge() {
  // @@protoc_insertion_point(field_release:castchannel.DeviceAuthMessage.challenge)
  clear_has_challenge();
  ::castchannel::AuthChallenge* temp = challenge_;
  challenge_ = NULL;
  return temp;
}
inline void DeviceAuthMessage::set_allocated_challenge(::castchannel::AuthChallenge* challenge) {
  delete challenge_;
  challenge_ = challenge;
  if (challenge) {
    set_has_challenge();
  } else {
    clear_has_challenge();
  }
  // @@protoc_insertion_point(field_set_allocated:castchannel.DeviceAuthMessage.challenge)
}

// optional .castchannel.AuthResponse response = 2;
inline bool DeviceAuthMessage::has_response() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DeviceAuthMessage::set_has_response() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DeviceAuthMessage::clear_has_response() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DeviceAuthMessage::clear_response() {
  if (response_ != NULL) response_->::castchannel::AuthResponse::Clear();
  clear_has_response();
}
inline const ::castchannel::AuthResponse& DeviceAuthMessage::response() const {
  // @@protoc_insertion_point(field_get:castchannel.DeviceAuthMessage.response)
  return response_ != NULL ? *response_
                         : *::castchannel::AuthResponse::internal_default_instance();
}
inline ::castchannel::AuthResponse* DeviceAuthMessage::mutable_response() {
  set_has_response();
  if (response_ == NULL) {
    response_ = new ::castchannel::AuthResponse;
  }
  // @@protoc_insertion_point(field_mutable:castchannel.DeviceAuthMessage.response)
  return response_;
}
inline ::castchannel::AuthResponse* DeviceAuthMessage::release_response() {
  // @@protoc_insertion_point(field_release:castchannel.DeviceAuthMessage.response)
  clear_has_response();
  ::castchannel::AuthResponse* temp = response_;
  response_ = NULL;
  return temp;
}
inline void DeviceAuthMessage::set_allocated_response(::castchannel::AuthResponse* response) {
  delete response_;
  response_ = response;
  if (response) {
    set_has_response();
  } else {
    clear_has_response();
  }
  // @@protoc_insertion_point(field_set_allocated:castchannel.DeviceAuthMessage.response)
}

// optional .castchannel.AuthError error = 3;
inline bool DeviceAuthMessage::has_error() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DeviceAuthMessage::set_has_error() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DeviceAuthMessage::clear_has_error() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DeviceAuthMessage::clear_error() {
  if (error_ != NULL) error_->::castchannel::AuthError::Clear();
  clear_has_error();
}
inline const ::castchannel::AuthError& DeviceAuthMessage::error() const {
  // @@protoc_insertion_point(field_get:castchannel.DeviceAuthMessage.error)
  return error_ != NULL ? *error_
                         : *::castchannel::AuthError::internal_default_instance();
}
inline ::castchannel::AuthError* DeviceAuthMessage::mutable_error() {
  set_has_error();
  if (error_ == NULL) {
    error_ = new ::castchannel::AuthError;
  }
  // @@protoc_insertion_point(field_mutable:castchannel.DeviceAuthMessage.error)
  return error_;
}
inline ::castchannel::AuthError* DeviceAuthMessage::release_error() {
  // @@protoc_insertion_point(field_release:castchannel.DeviceAuthMessage.error)
  clear_has_error();
  ::castchannel::AuthError* temp = error_;
  error_ = NULL;
  return temp;
}
inline void DeviceAuthMessage::set_allocated_error(::castchannel::AuthError* error) {
  delete error_;
  error_ = error;
  if (error) {
    set_has_error();
  } else {
    clear_has_error();
  }
  // @@protoc_insertion_point(field_set_allocated:castchannel.DeviceAuthMessage.error)
}

inline const DeviceAuthMessage* DeviceAuthMessage::internal_default_instance() {
  return &DeviceAuthMessage_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace castchannel

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::castchannel::CastMessage_ProtocolVersion> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::castchannel::CastMessage_PayloadType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::castchannel::AuthError_ErrorType> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_stream_5fout_2fchromecast_2fcast_5fchannel_2eproto__INCLUDED
